version: '3.9'
services:
  postgres:
    image: postgres
    container_name: flow-view-postgres-container
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flow-view
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://localhost:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"

volumes:
  pgdata:
  waha_sessions:
  waha_media: